export const mentorConstants={
    GET_MENTOR_BY_ID_SUCCESS:"GET_MENTOR_BY_ID_SUCCESS",
    GET_MENTOR_BY_ID_REQUEST:"GET_MENTOR_BY_ID_REQUEST",
    GET_MENTOR_BY_ID_FAILED:"GET_MENTOR_BY_ID_FAILED",
    GET_ALL_MENTORS_REQUEST:"GET_ALL_MENTORS_REQUEST",
    GET_ALL_MENTORS_SUCCESS:"GET_ALL_MENTORS_SUCCESS",
    GET_ALL_MENTORS_FAILED:"GET_ALL_MENTORS_FAILED",
    ADD_MENTOR_REQUEST:"ADD_MENTOR_REQUEST",
    ADD_MENTOR_SUCCESS:"ADD_MENTOR_SUCCESS",
    ADD_MENTOR_FAILED:"ADD_MENTOR_FAILED",
}

export const resourseConstants={
    GET_ALL_RESOURCES_REQUEST:"GET_ALL_RESOURCES_REQUEST",
    GET_ALL_RESOURCES_SUCCESS:"GET_ALL_RESOURCES_SUCCESS",
    GET_ALL_RESOURCES_FAILED:"GET_ALL_RESOURCES_FAILED",
    ADD_RESOURCES_REQUEST:"ADD_RESOURCES_REQUEST",
    ADD_RESOURCES_SUCCESS:"ADD_RESOURCES_SUCCESS",
    ADD_RESOURCES_FAILED:"ADD_RESOURCES_FAILED",
    GET_RESOURCES_BY_MENTOR_ID_REQUEST:"GET_RESOURCES_BY_MENTOR_ID_REQUEST",
    GET_RESOURCES_BY_MENTOR_ID_SUCCESS:"GET_RESOURCES_BY_MENTOR_ID_SUCCESS",
    GET_RESOURCES_BY_MENTOR_ID_FAILED:"GET_RESOURCES_BY_MENTOR_ID_FAILED",
}

export const historyConstants={
    GET_HISTORY_BY_ID_REQUEST:"GET_HISTORY_BY_ID_REQUEST",
    GET_HISTORY_BY_ID_SUCCESS:"GET_HISTORY_BY_ID_SUCCESS",
    GET_HISTORY_BY_ID_FAILED:"GET_HISTORY_BY_ID_FAILED",
    ADD_HISTORY_REQUEST:"ADD_HISTORY_REQUEST",
    ADD_HISTORY_SUCCESS:"ADD_HISTORY_SUCCESS",
    ADD_HISTORY_FAILED:"ADD_HISTORY_FAILED",
}

export const eventConstants={
    GET_ALL_EVENTS_REQUEST:"GET_ALL_EVENTS_REQUEST",
    GET_ALL_EVENTS_SUCCESS:"GET_ALL_EVENTS_SUCCESS",
    GET_ALL_EVENTS_FAILED:"GET_ALL_EVENTS_FAILED",
    ADD_EVENT_REQUEST:"ADD_EVENT_REQUEST",
    ADD_EVENT_SUCCESS:"ADD_EVENT_SUCCESS",
    ADD_EVENT_FAILED:"ADD_EVENT_FAILED",
    GET_EVENT_BY_ID_REQUEST:"GET_EVENT_BY_ID_REQUEST",
    GET_EVENT_BY_ID_SUCCESS:"GET_EVENT_BY_ID_SUCCESS",
    GET_EVENT_BY_ID_FAILED:"GET_EVENT_BY_ID_FAILED",
    GET_EVENT_BY_MENTOR_ID_REQUEST:"GET_EVENT_BY_MENTOR_ID_REQUEST",
    GET_EVENT_BY_MENTOR_ID_SUCCESS:"GET_EVENT_BY_MENTOR_ID_SUCCESS",
    GET_EVENT_BY_MENTOR_ID_FAILED:"GET_EVENT_BY_MENTOR_ID_FAILED",
    DELETE_EVENT_BY_ID_REQUEST:"DELETE_EVENT_BY_ID_REQUEST",
    DELETE_EVENT_BY_ID_SUCCESS:"DELETE_EVENT_BY_ID_SUCCESS",
    DELETE_EVENT_BY_ID_FAILED:"DELETE_EVENT_BY_ID_FAILED",
}

export const blogsConstants = {
    GET_ALL_BLOGS_REQUEST: "GET_ALL_BLOGS_REQUEST",
    GET_ALL_BLOGS_SUCCESS: "GET_ALL_BLOGS_SUCCESS",
    GET_ALL_BLOGS_FAILED: "GET_ALL_BLOGS_FAILED",
    GET_BLOGS_BY_AUTHOR_ID_REQUEST: "GET_BLOGS_BY_AUTHOR_ID_REQUEST",
    GET_BLOGS_BY_AUTHOR_ID_SUCCESS: "GET_BLOGS_BY_AUTHOR_ID_SUCCESS",
    GET_BLOGS_BY_AUTHOR_ID_FAILED: "GET_BLOGS_BY_AUTHOR_ID_FAILED",
}

export const authConstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
}
